# EZBlocks configuration file

sql:

  # Supported drivers: MySQL, MariaDB, H2 and PostgreSQL.
  # Use H2 for flat-file storage (default)
  driver: H2

  address: localhost:3306
  database: ezblocks
  username: root
  password: ''

# Hikari connection pool settings
pool:

  # Maximum concurrent connections
  max_connections: 10

  # Connection timeout, in milliseconds
  timeout: 30000 # 30 seconds

  # Idle timeout, in milliseconds
  idle_timeout: 60000 # 1 minute

 # Hooks for other plugins
hooks:

  #allow exploded blocks to be counted
  tokenenchant: false

# Blacklist blocks from being counted in blocks mined statistics and pickaxe counter
# materials can be found here for 1.16: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
excluded_blocks:
  - DIRT

# Blacklist worlds from being counted in blocks mined statistics and pickaxe counter
excluded_worlds:
  - world_the_end

messages:
  blocks_broken: '&fYou have broke &b%blocks% &fblocks!'

rewards:
  global_rewards:
    default:
      blocks_needed: 100 # 100 blocks are needed to execute these rewards
      commands:
        - '[message] &aYou have mined 100 blocks!'
        - '[command] eco give %player_name% 10'
  interval_rewards:
    default:
      blocks_needed: 100 # every 100 blocks rewards are given
      commands:
        - '[give] DIAMOND 1'
        - '[  '