name: EZBlocks
version: @version@
api-version: 1.13
main: me.clip.ezblocks.EZBlocks
depend: [PlaceholderAPI]
softdepend: [TokenEnchant]
authors: [extended_clip, katsumag, BomBardyGamer, Kaliber]
description: "Count player's blocks broken"

commands:
  ezblocks:
    description: main command
    usage: /ezblocks

permissions:
  ezblocks.check:
    description: access to check others blocks broken by command
    default: op
  ezblocks.pickaxecounter:
    description: ability to have a pickaxe counter
    default: op
  ezblocks.admin:
    description: access to admin commands
    default: op